baseURL = "https://aegisanaturale.com"
languageCode = "en-us"
title = "aegisa Site"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true